### ISSUE TITLE
null transform

### ISSUE THREAD

**Issue by orangepeelbeef** [michaelpittino/BlackResearch#2]
Is there a transform that we can apply to tell it to ignore the packet or it actually must be processed?

keep getting null transform on the encrypted stuff.  assuming its left out on purpose for reasons how would i just ignore those bits?

**Comment by Yothri** [comment]
currently transformer doesnt work because the encryption has changed.
opendesesrtproject.com someone posted the new crypto but its in C.
You can export the functions and PInvoke them or you convert the C code to c#.
But yeah, needs some work.

**Comment by michaelpittino** [comment]
See: https://github.com/michaelpittino/Oasis
